---
- name: deploy - Add user
  user:
    name: "{{ app_deploy_user_name }}"
    home: "{{ app_deploy_user_home }}"
    createhome: yes
    system: yes
    state: present

- name: deploy - Clone repository
  git:
    repo: "{{ app_deploy_repo }}"
    dest: "{{ app_deploy_location }}"
    version: master
  become_user: "{{ app_deploy_user_name }}"
  register: source
  notify: Restart app

- name: debug source var
  debug:
    var: source

- name: deploy - Bundle install
  command: bundle install --deployment
  args:
    chdir: "{{ app_deploy_location }}"
  become_user: "{{ app_deploy_user_name }}"
  when: source.changed
  notify: Restart app

- name: deploy - Add init script
  template:
    src: "templates/init.conf.j2"
    dest: "/etc/init/{{ app_deploy_name }}.conf"
    owner: root
    group: root
    mode: 0755

- name: deploy - Enable service
  service:
    name: "{{ app_deploy_name }}"
    enabled: yes

